#ifndef _CBASEDEFINE_H_
#define _CBASEDEFINE_H_

typedef enum
{
	COBRA_OBJECT,
	COBRA_ACTIVITY,
	COBRA_SERVICES,
	COBRA_OBSERVER,
	COBRA_RESPONSE,
	COBRA_INTENT,
	COBRA_BUNDLE,
	COBRA_COMMAND,
} cCobraObjType;

#endif //_CBASEDEFINE_H_