#ifndef _CPLATFORMDEFINE_H_
#define _CPLATFORMDEFINE_H_

#define COBRA_RENDEENQINE_UNKNOWN				0
#define COBRA_RENDEENQINE_COCOS2DX				1
#define COBRA_RENDEENQINE_IRRLICHT				2

#define COBRA_TARGET_RENDEENQINE             COBRA_RENDEENQINE_COCOS2DX

#if (COBRA_TARGET_RENDEENQINE == COBRA_RENDEENQINE_COCOS2DX)
#define COBRA_LOG(condition,msg)		CCAssert(condition,msg)
#endif


#if (COBRA_TARGET_RENDEENQINE == COBRA_RENDEENQINE_COCOS2DX)
	#include "cocos2d.h"
	USING_NS_CC;
#endif
#endif	//_CPLATFORMDEFINE_H_