#ifndef _CRESPONSE_H_
#define _CRESPONSE_H_

#include "CCobraObject.h"

typedef enum
{
	RESPONSE_UNKOWN,
	RESPONSE_START_ACTIVITY_SUCCESS,
	RESPONSE_START_ACTIVITY_FAILURE,
	RESPONSE_CODE_SUCCESS,
	RESPONSE_CODE_FAILURE,
	RESPONSE_BIND_SERVICE_SUCCESS,
	RESPONSE_BIND_SERVICE_FAILURE,
	RESPONSE_HAS_BINDED,
	RESPONSE_GET_ACTIVITY_SUCCESS,
	RESPONSE_GET_ACTIVITY_FAILURE,
	RESPONSE_GET_SERVICE,
	RESPONSE_LOAD_GUI_SUCCESS,
	RESPONSE_UNLOAD_GUI_SUCCESS,
	RESPONSE_FINISH_ACTIVITY_SUCCESS,
	RESPONSE_FINISH_ACTIVITY_FAILURE,
} bResponseCode;


class CBundle;

class CResponse : public CCobraObject
{
public:
	CResponse(void);
	virtual ~CResponse(void);

	COBRA_CREATE_PROPERTY(int,m_eRespCode,RespCode)
	COBRA_CREATE_PROPERTY(CCobraObject*,m_pTarget,RespTarget)
	COBRA_CREATE_PROPERTY(CBundle*,m_pBundle,Bundle)
};

#endif